apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-self-signed
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selfSigned: {}
