apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-self-signed
  annotations:
    "helm.sh/hook": "post-install"
    argocd.argoproj.io/sync-wave: "100"
spec:
  selfSigned: {}
