apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-server-tls-secret
spec:
  dnsNames:
    - turing.servehttp.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: issuer-letsencrypt-staging
  secretName: echo-server-tls-secret