---
- name: Setup init node
  when: inventory_hostname == groups['server'][0]
  block:
  - name: Running cluster-init on node {{ groups['server'][0] }}
    ansible.builtin.command:
      cmd: /usr/local/bin/k3s-install.sh --cluster-init --token {{ k3s.token }} {{ k3s.extra_server_args }}

  - name: Wait until /etc/rancher/k3s/k3s.yaml is present before continuing
    ansible.builtin.wait_for:
      path: /etc/rancher/k3s/k3s.yaml

  - name: Wait node {{ groups['server'][0] }} became ready
    ansible.builtin.command:
      cmd: sudo KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl wait --for=condition=Ready nodes --all --timeout=600s

- name: Setup additonal nodes
  when: inventory_hostname != groups['server'][0]
  block:
    - name: Adding server nodes
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh --server https://{{ k3s.endpoint }}:6443 --token {{ k3s.token }} {{ k3s.extra_server_args }}