---
- name: Setup agent
  block:
    - name: Adding agent node
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh agent --disable=traefik --server https://{{ k3s.endpoint }}:6443 --token {{ k3s.token }} {{ k3s.extra_agent_args }}