apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  sources:
    - chart: argo-cd
      repoURL:  https://argoproj.github.io/argo-helm
      targetRevision: 9.3.0
      helm:
        values: |
          redis-ha:
            enabled: false
          controller:
            replicas: "1"
          server:
            replicas: "1"
          repoServer:
            replicas: "1"
          applicationSet:
            replicaCount: "1"
          commitServer:
            enabled: true
          configs:
            params:
              "server.insecure": "true"
              "hydrator.enabled": "true"
            cm:
              "exec.enabled": "true"
              "timeout.reconciliation": "120s"
              "resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition": |
                jsonPointers:
                - /spec/preserveUnknownFields
              "resource.customizations.health.argoproj.io_Application": |
                hs = {}
                hs.status = "Progressing"
                hs.message = ""
                if obj.status ~= nil then
                  if obj.status.health ~= nil then
                    hs.status = obj.status.health.status
                    if obj.status.health.message ~= nil then
                      hs.message = obj.status.health.message
                    end
                  end
                end
                return hs
          dex:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
