apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  sources:
    - chart: argo-cd
      repoURL:  https://argoproj.github.io/argo-helm
      targetRevision: 7.3.7
      helm:
        values: |
          redis-ha:
            enabled: false
          controller:
            replicas: "1"
          server:
            replicas: "1"
          repoServer:
            replicas: "1"
          applicationSet:
            replicaCount: "1"
          configs:
            params:
              "server.insecure": "true"
              "server.rootpath": "/argocd"
            cm:
              "exec.enabled": "true"
              "timeout.reconciliation": "30s"
          dex:
            enabled: false
    - path: ./kubernetes-services/additions/argo-cd
      repoURL: https://github.com/procinger/turing-pi-v2-cluster.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
