apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  sources:
    - chart: argo-cd
      repoURL:  https://argoproj.github.io/argo-helm
      targetRevision: 8.0.10
      helm:
        values: |
          redis-ha:
            enabled: false
          controller:
            replicas: "1"
          server:
            replicas: "1"
          repoServer:
            replicas: "1"
          applicationSet:
            replicaCount: "1"
          commitServer:
            enabled: true
          configs:
            params:
              "server.insecure": "true"
              "hydrator.enabled": "true"
            cm:
              "exec.enabled": "true"
              "timeout.reconciliation": "120s"
              "resource.compareoptions": |
                ignoreResourceStatusField: crd
          dex:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
