apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: kubernetes
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.19.1
      helm:
        values: |
          prometheus:
            enabled: true
          installCRDs: true
          # https://cert-manager.io/v1.9-docs/usage/gateway/
          extraArgs:
           - --feature-gates=ExperimentalGatewayAPISupport=true
    - path: ./kubernetes-services/additions/cert-manager
      repoURL: https://github.com/procinger/turing-pi-v2-cluster.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
