apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  project: kubernetes
  sources:
    - path: ./kubernetes-services/additions/cloudflare-tunnel
      repoURL: https://github.com/procinger/turing-pi-v2-cluster.git
      targetRevision: feat/cloudflare-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
