apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: kubernetes
  ignoreDifferences:
    - kind: ValidatingWebhookConfiguration
      group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.28.2
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      helm:
        values: |
          pilot:
            env:
              PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
              K8S_INGRESS_NS: "istio-gateway"
            autoscaleEnabled: false
            replicaCount: 2
          global:
            proxy:
              tracer: "zipkin"
          meshConfig:
            ingressService: istio-gateway
            ingressSelector: gateway
            defaultConfig:
              tracing:
                zipkin:
                  address: "istio-system-jaeger-collector.istio-system:9411"
      targetRevision: 1.28.2
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-server
      targetRevision: 2.20.0
      helm:
        values: |
          clustering:
            autodetect_secrets:
              enabled: false
          kiali_feature_flags:
            validations:
              ignore: ["KIA1106"]
              skip_wildcard_gateway_hosts: true
          external_services:
            prometheus:
              url: "http://prometheus-kube-prometheus-prometheus.monitoring:9090/"
            grafana:
              enabled: true
              internal_url: "http://prometheus-grafana.monitoring:80"
            tracing:
              internal_ur: "http://istio-system-jaeger-query:16685/jaeger"
              use_grpc: true
            istio:
              root_namespace: istio-system
              component_status:
                enabled: true
                components:
                - app_label: istiod
                  is_core: true
                - app_label: istio-gateway
                  is_core: true
                  is_proxy: true
                  namespace: istio-gateway
    - repoURL: https://jaegertracing.github.io/helm-charts
      chart: jaeger
      targetRevision: 4.3.4
      helm:
        values: |
          query:
            enabled: false
          provisionDataStore:
            cassandra: false
          allInOne:
            enabled: true
          storage:
            type: memory
          agent:
            enabled: false
          collector:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
