apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  project: kubernetes
  sources:
    - chart: kargo
      repoURL: ghcr.io/akuity/kargo-charts
      targetRevision: 1.5.0
      helm:
        values: |
          api:
            # hardcoded login credentials
            # in production systems should use oidc!
            adminAccount:
              passwordHash: "$2a$12$/fHRdnXaUYBicfR0BsKh/.el6l4O/o.fEeGI7yyOjchEIfYj5Mh.K"
              tokenSigningKey: AbAugOWkStfbwczR8wQooceM3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true