apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kured
  project: kubernetes
  source:
    chart: kured
    repoURL: https://kubereboot.github.io/charts
    targetRevision: 5.5.2
    helm:
      values: |
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "250m"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
