apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kured
  project: kubernetes
  source:
    chart: kured
    repoURL: https://kubereboot.github.io/charts
    targetRevision: 5.4.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
