---
- name: Preparing Storage
  block:
  - name: Creating a filesystem on block device
    community.general.filesystem:
      fstype: "{{ storage.filesystem }}"
      dev: "{{ storage.block_device }}"

  - name: Mount block device
    ansible.posix.mount:
      path: /var/lib/longhorn
      src: "{{ storage.block_device }}"
      fstype: "{{ storage.filesystem }}"
      boot: true
      opts: defaults
      state: mounted
  when: storage.block_device is defined and storage.filesystem is defined
