---
- name: Preparing Storage
  when: storage.block_device is defined and not ansible_facts.mounts | selectattr('mount', '==', '/') | selectattr('device', '==', "storage.block_device") | length == 0
  block:

  - name: Installing root filesystem on block device {{ storage.block_device }}
    ansible.builtin.shell: |
      yes | /usr/bin/ubuntu-rockchip-install {{ storage.block_device }}

  - name: Reboot the server to run from {{ storage.block_device }}
    ansible.builtin.reboot:
