apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-services
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: kubernetes
  source:
    path: ./kubernetes-services
    repoURL: https://github.com/procinger/turring-pi-v2-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true