name: Helm Chart Changes
on:
  merge_group:
  pull_request:
    paths:
      - kubernetes-services/**
      - test/**

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          kubectl: '1.29.0'
          helm: '3.15.1'
      - uses: mikefarah/yq@v4.44.2
      - uses: tj-actions/changed-files@v45.0.4
        id: changed-argo-apps
        with:
          files_yaml: |
            apps:
              - kubernetes-services/templates/**
              - '!kubernetes-services/templates/istio**.yaml'
            istio:
              - kubernetes-services/templates/istio**
            go_test:
              - test/**_test.go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum
      - name: Test Common Helm Chart
        if: steps.changed-argo-apps.outputs.apps_any_changed == 'true'
        env:
          HELM_CHARTS_CHANGED_FILES: ${{ steps.changed-argo-apps.outputs.apps_all_changed_files }}
        run: |
          echo "List all helm charts that have changed"
          for chart in ${HELM_CHARTS_CHANGED_FILES}; do
            echo "${chart} was changed"
            
            test="test/$(basename ${chart} | sed -E 's/-([a-z])/_\1/g' | sed 's/.yaml/_test.go/')"
            if [ ! -f ${test} ]; then
              echo "Test coverage ${test} not found. bye!"
              exit 2
            fi
          
            go test -v ./test -run $(basename ${chart} .yaml | sed 's/.*/Test\u&/' | sed -E 's/-([a-z])/\U\1/g')
          done
      - name: Test Istio Helm Chart
        if: steps.changed-argo-apps.outputs.istio_any_changed == 'true'
        env:
          HELM_CHARTS_CHANGED_FILES: ${{ steps.changed-argo-apps.outputs.istio_all_changed_files }}
        run: |
          go test -v ./test -run TestIstio
      - name: Golang Tests
        if: steps.changed-argo-apps.outputs.go_test_any_changed == 'true'
        env:
          GO_TEST_CHANGED_FILES: ${{ steps.changed-argo-apps.outputs.go_test_all_changed_files }}
        run: |
          for test in ${GO_TEST_CHANGED_FILES}; do
          echo "${test} was changed"
            go test -v ./test -run $(basename ${test} _test.go | sed 's/.*/Test\u&/' | sed -E 's/_([a-z])/\U\1/g')
          done
      - name: Upload KinD logs
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kind
          path: 'test/kind-logs'
          retention-days: 3
