name: Helm Chart Changes
on:
  pull_request:
    paths:
      - kubernetes-services/**
      - test/**

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          kubectl: '1.29.0'
          helm: '3.15.1'
      - uses: mikefarah/yq@v4.44.2
      - uses: tj-actions/changed-files@v44
        id: changed-argo-apps
        with:
          files_yaml: |
            apps:
              - kubernetes-services/templates/**
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: go.sum
      - name: Test Helm Chart
        if: steps.changed-argo-apps.outputs.apps_any_changed == 'true'
        env:
          APPS_ALL_CHANGED_FILES: ${{ steps.changed-argo-apps.outputs.apps_all_changed_files }}
        run: |          
          if [ ! -f "test/$(basename ${APPS_ALL_CHANGED_FILES} | sed -E 's/-([a-z])/_\1/g' | sed 's/.yaml/_test.go/')" ]; then
            echo "Test coverage not found. bye!"
            exit 2
          fi
          
          export PATH=$PATH:bin
          echo "List all the files that have changed: $APPS_ALL_CHANGED_FILES"
          go test -v ./test -run $(basename ${APPS_ALL_CHANGED_FILES} .yaml |  sed 's/.*/Test\u&/' | sed -E 's/-([a-z])/\U\1/g')
